# Generated by Django 3.0.5 on 2023-04-19 05:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppifyPage', '0004_shoppingpage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingpage',
            name='price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=7),
        ),
    ]
