# Generated by Django 3.0.5 on 2023-04-20 18:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppifyPage', '0006_remove_shoppingpage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingpage',
            name='price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=3),
        ),
    ]
