# Generated by Django 3.0.5 on 2023-04-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppifyPage', '0007_shoppingpage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingpage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppingpage',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
