# Generated by Django 3.0.5 on 2023-04-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppifyPage', '0008_auto_20230421_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingpage',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
