# Generated by Django 3.0.5 on 2023-05-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppifyPage', '0012_shoppingpage_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingpage',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
