# Generated by Django 3.0.5 on 2023-05-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppifyPage', '0013_auto_20230505_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingpage',
            name='username',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
